build_defaults: &build_defaults
  working_directory: ~/testing_web3js
  steps:
    - checkout
    - run: sudo apt-get install --yes curl
    - run: curl --silent --location https://deb.nodesource.com/setup_4.x | sudo bash -
    - run: sudo apt-get install --yes nodejs
    - run: sudo apt-get install --yes build-essential

version: 2
jobs:
  build_16:
    <<: *build_defaults
    docker:
      - image: ubuntu:16.04

  build_14:
    <<: *build_defaults
    docker:
      - image: ubuntu:14.04

  build_18:
    <<: *build_defaults
    docker:
      - image: ubuntu:18.04 

  build_12:
    <<: *build_defaults
    docker:
      - image: ubuntu:12.04

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_16
      # - build_14:
      #     requires:
      #       - build_16
      # - build_18:
      #     requires:
      #       - build_14
      # - build_12:
      #     requires:
      #       - build_18